### ISSUE TITLE
AutoLayout issue

### ISSUE THREAD

**Issue by anthonycastelli** [CVCalendar/CVCalendar#159]
When testing this against different size classes, the calendar doesn't appears to resize itself properly. 

Here is a screenshot of the calendarView stretched in the horizontal orientation of the iPhone 6S Plus. 

<img width="1061" alt="screen shot 2015-11-09 at 6 23 14 pm" src="https://cloud.githubusercontent.com/assets/2137365/11052702/63654c36-870f-11e5-85ba-632849708c85.png">

**Comment by anthonycastelli** [comment]
Has there been any progress on this? I've looked at the library to see if I could find the broken constraint or match but didn't seem to find it. If anyone has any ideas on where it might be stemming from I could work on a fix but I just don't know where to begin.

**Comment by trinhngocthuyen** [comment]
I also encounter the same issue. Has anyone figured out how to solve it?

**Comment by elsesiy** [comment]
@anthonycastelli @trinhngocthuyen Not so far no, we're working on several issues atm and hopefully will be able to consider this one soon, too! I need to ask you for a little patience or feel free to contribute and submit a PR :+1:

**Comment by anthonycastelli** [comment]
I’ve looked into the the issue, but I’m not the best when it comes to Autolayout strictly in code, so if anyone is better, please have a look at this. This issue is the only major one left in my app.

**Comment by kostapappas** [comment]
putting this subviews into stackview and added to all autolayout constrains programmatically solved my same problem.

**Comment by anthonycastelli** [comment]
@kostapappas When I throw the CVCalendarView and CVCalendarMenuView in a UIStackView it just shows a blank view with nothing inside of it. How did you achieve this?

**Comment by schdef** [comment]
I did some debugging and figured out that the layouting method **commitCalendarViewUpdate** (https://github.com/Mozharovsky/CVCalendar/blob/master/CVCalendar/CVCalendarView.swift#L206) is called for my app on an iphone 5 and 6+ three times, on an iphone 6 just once. The width isn't calculated correct on the first call, but in the second one. The "validated" flag in that method prevents the width calculation for any upcoming call, so that's why this issue occurs.

Because I couldn't change that behaviour in the library, I copy&paste the method with some modification. Now it looks like this:
```
extension CVCalendarView {
    public func commitCalendarViewUpdate() {
        if let _ = delegate, let contentController = contentController {
            let contentViewSize = contentController.bounds.size
            let selfSize = bounds.size
            let screenSize = UIScreen.mainScreen().bounds.size
            
            let allowed = selfSize.width <= screenSize.width && selfSize.height <= screenSize.height
            
            if !validated && allowed {
                let width = selfSize.width
                let height: CGFloat
                let countOfWeeks = CGFloat(6)
                
                let vSpace = appearance.spaceBetweenWeekViews!
                let hSpace = appearance.spaceBetweenDayViews!
                
                if let mode = calendarMode {
                    switch mode {
                    case .WeekView:
                        height = selfSize.height
                    case .MonthView :
                        height = (selfSize.height / countOfWeeks) - (vSpace * countOfWeeks)
                    }
                    
                    // If no height constraint found we set it manually.
                    var found = false
                    for constraint in constraints {
                        if constraint.firstAttribute == .Height {
                            found = true
                        }
                    }
                    
                    if !found {
                        addConstraint(NSLayoutConstraint(item: self, attribute: .Height, relatedBy: .Equal, toItem: nil, attribute: .Height, multiplier: 1, constant: frame.height))
                    }
                    
                    weekViewSize = CGSizeMake(width, height)
                    dayViewSize = CGSizeMake((width / 7.0) - hSpace, height)
                    validated = true
                    
                    contentController.updateFrames(selfSize != contentViewSize ? bounds : CGRectZero)
                }
            }
        }
    }
}
```

Main change is to check if the width is different than the first call, to allow a new width calculation and layouting. It doesn't need to be an extension, because I'm calling this method right after the **commitCalendarViewUpdate** in the ViewController:
```
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        calendarView.commitCalendarViewUpdate()
        menuView.commitMenuViewUpdate()
        
        calendarView.redrawViewIfNecessarry()
    }
```

Hope it helps someone.

**Comment by elsesiy** [comment]
@schdef Thanks for pointing that out. Could you please submit a PR?

**Comment by elsesiy** [comment]
Fixed in #384

**Comment by KimPark89** [comment]
Hi, thanks for this awesome library.

I was testing the iOS 9 multitasking mode (split view) and I noticed that when I resize the view, the calendar doesn't refresh his layout properly.

Any idea on how to solve?

![simulator-screen-shot-11-feb-2017 -19 54 00](https://cloud.githubusercontent.com/assets/10373473/22856567/239bbf6e-f094-11e6-85b4-2fa744743ed1.png)

**Comment by sategroup** [comment]
@schdef , @elsesiy Infact, this issue persists not only with width, but height also. I used the same code to re-calculate height when using CVCalendar inside stack and it worked.

There is definitely a problem using CVCalendar inside stack. It simple stops working. In my case, it wasn't able to calculate height properly and the method executed twice. But, as @schdef pointed second time validation flag didn't allow it to re-calculate things. 

In order to reproduce, put calendar and menu inside a view controller, stack them both. Now, run the code with your layout constraints and notice that calendar dates are not visible though menu appears fine. I tested in portrait mode.

**Comment by elsesiy** [comment]
@sategroup Can you provide a sample project please?

**Comment by leojkwan** [comment]
@schdef  Thanks for that fix. This problem is still prevalent in CVCalendar.

Here is Swift 4 version of the extension Fix

```
extension CVCalendarView {

  public func redrawViewIfNecessarry() {
    let contentViewSize = contentController.bounds.size
    let selfSize = bounds.size
    if selfSize.width != contentViewSize.width {
      let width = selfSize.width
      let height: CGFloat
      let countOfWeeks = CGFloat(6)

      let vSpace = appearance.spaceBetweenWeekViews!
      let hSpace = appearance.spaceBetweenDayViews!

      if let mode = calendarMode {
        switch mode {
        case .weekView:
          height = selfSize.height
        case .monthView:
          height = (selfSize.height / countOfWeeks) - (vSpace * countOfWeeks)
        }

        // If no height constraint found we set it manually.
        var found = false
        for constraint in constraints {
          if constraint.firstAttribute == .height {
            found = true
          }
        }

        if !found {
          addConstraint(NSLayoutConstraint(item: self, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .height, multiplier: 1, constant: frame.height))
        }

        weekViewSize = CGSize(width: width, height: height)

        dayViewSize = CGSize(width: (width / 7.0) - hSpace, height: height)

        contentController.updateFrames(selfSize != contentViewSize ? bounds : CGRect.zero)
      }
    }
  }

}

```

**Comment by elsesiy** [comment]
@leojkwan Please submit a PR with these changes if you have time to do so. I currently can't properly support this project anymore so any contribution is highly appreciated.

**Comment by jose-rodri** [comment]
Hola Alguien sabe como quitar , remover ó desactivar ese efecto de AutoLayout de Calendario , le agregue un tamaño  peor no resulta , si el mes trae  4 semanas se auto ajusta a ese tamaño y si el mes tiene 5 semanas se hace mas grande .
