### ISSUE TITLE
ERROR IN SELECTING THE DAY

### ISSUE THREAD

**Issue by schulz89sp** [CVCalendar/CVCalendar#444]
- [Y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y] I have verified that I am using the latest version of CVCalendar.
- [Y] I have given my issue a non-generic title.

## Expected Behavior
Why when I pick one day in the month and is selected with the blue around and the day becomes white, then if I go to the view of the week, the day remains in white and the blue circle is gone?

## Your Environment
* Version used (Cocoapods spec): Latest version
* Device used i.e. iPhone 5S:

**Comment by RSickenberg** [comment]
Same here for Iphone 6S !

**Comment by elsesiy** [comment]
@schulz89sp @RSickenberg is this still a problem? I'm not able to reproduce it so you need to provide a sample project or a detailed explanation on your setup or otherwise I won't be able to help.

**Comment by schulz89sp** [comment]
When the app starts in month.view, if I select a day of the same week it is selected correctly with the blue background and the number becomes white ... but if I then do the week.view the blue background disappears and the number remains white , So with the white background of my app you can not see ...
If then from week.view I choose another day, everything is back.

**Comment by dhsu210** [comment]
@elsesiy I think in general there might be something going on with `dayLabelBackgroundColor` as my background color (circle) disappears on my month view initially as well

**Comment by davidvpe** [comment]
Same issue here, when calendar view initializes the present day appears blank, I have to select other day in order to change the color on the present date.

**Comment by dhsu210** [comment]
I managed to get CVCalendar to work for my purposes. One suggestion I can make for others is to put breakpoints on each of the delegate functions to see exactly when they are hit. In my use case, I wanted to present a pre-selected date (with the circle view popping up) when the calendar first loads, then move forward and backwards to other months. Whenever coming back to the original month, I wanted the pre-selected date to show up again with the correct selected color and background circle color. To get all of this to work, I basically did a few things:

- saved the month component of the initially presented month view in an Int var
- call `toggleViewWithDate` in `viewDidAppear` and in the functions triggered by the months going forward or backward (only when the month component matched)
- created a `previouslySelectedDayView` bool (what you will notice with your breakpoints inside of `dayLabelColor` and `dayLabelBackgroundColor` is that these functions will hit the actual day twice on the actual presented day) which I use to control which color should show up. So for example, if the day is May 23, Tues -- the breakpoint will run through M, Tu, Wed, Thurs...all the previous days up until May 23, which it will run twice triggering the .selected and .present properties. My suggestion is to play with the breakpoints to find the right combination of the properties you want for when you want to display the "blank" present day. It's not blank, it's just that the set UIColor doesn't show up if it's white on white.

Something like this (and you would do the same for dayLabelColor): 
`func dayLabelBackgroundColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        
        if status == .selected && present == .present {
            // Set previouslySelectedDayView to true -- for case where selected date falls on current date --> it will then hit .in && .present case (in which case we want to have white color font)
            previouslySelectedDayView = true
            return Color.background
        }
        
        switch (weekDay, status, present) {
        case (_, .selected, _): return Color.selectionBackground
        case (_, _, .present):
            if previouslySelectedDayView && !currentDayView {
                return Color.selectionBackground
            }
            return Color.background
        default: return nil
        }
    }`

- Another suggestion is to call `calendarView.coordinator.flush()` before you call `toggleViewWithDate` to "clean" out your calendar saved dayViews etc.

I know the above seems like a lot of work to fine-tune but once you get it working, the UI and everything comes together quite beautifully. I hope this helps you guys a bit!

**Comment by chadpardoe** [comment]
I have noticed this same issue in 1.5.0 with the same steps to reproduce schulz89sp describes. 

Reverting to 1.4.1 the bug is not present.

**Comment by ravelinx22** [comment]
Having the same issue here, The present day if selected at start appears white

**Comment by Bullas** [comment]
hI!
I just had the same issue. 
What worked for me

self.selectedDay.isHighlighted = false
self.selectedDay.setSelectedWithType(SelectionType.single)

selectedDay = Dayview

set it manually

**Comment by rocket-enterprise** [comment]
Where do you set this Bullas?

**Comment by elsesiy** [comment]
This is related to #461

**Comment by elsesiy** [comment]
The issue has been resolved in the latest master. Please test again so I can draft a release, thanks.

**Comment by elsesiy** [comment]
Any feedback would be appreciated so I can move on..

**Comment by egie19** [comment]
Hi elsesiy, I'm still encountering the issue when using 1.5.0 version.

**Comment by elsesiy** [comment]
Pod `1.5.1` should fix this issue.
