### ISSUE TITLE
Appearance.delegate influencing textColor only after two page scrolls

### ISSUE THREAD

**Issue by timroesner** [CVCalendar/CVCalendar#571]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
Implementing `dayLabelWeekdayInTextColor()` in the delegate should effect textColor immediately. 

## Current Behavior
I need to do two page scrolls before it effects the textColor. 

## Possible Solution
Not sure. Poked around the methods setting the textColor but could not find a fix.

## Steps to Reproduce (for bugs)
1. Implement `CVCalendarViewAppearanceDelegate`
2. Set Delegate to self
3. 
```swift
    func dayLabelWeekdayInTextColor() -> UIColor {
        return .blue
    }
```

## Context
I found this issue while trying to improve this framework for dark mode. I'm happy to do a PR and use the new colors.

## Your Environment
Swift 4.2
Xcode 11
macOS Catalina

**Comment by elsesiy** [comment]
Hi @timroesner, since you opened #572 which I just merged I assume your issue has been resolved?

**Comment by timroesner** [comment]
Hi @elsesiy, the issue still exists. The PR changes the default colors. This issue however has to do with the appearance.delegate.

**Comment by RobSwish** [comment]
Can anyone shine some light on this one for me? Where do I set the appearance information? I've set it in my viewDidLoad and it only applies my styles to the calendar after two pages scrolls? Thank you

**Comment by RobSwish** [comment]
Okay so I sorted this issue, and here's how I did it, maybe this will help someone one day...

Important thing to note: 
1. The read me for this states that you need to set the appearance delegate before the calendar delegate.

However, when I did this it would crash, because I hadn't created the Appearance object yet and assigned it to calendar.appearance. 

Once I did that it all worked fine. 

Final code snippet for reference:

`//Set appearance styles
        appearance.dayLabelWeekdaySelectedBackgroundColor = .accentSecondary
        
        //Assign appearance delegate
        calendarView.appearance = appearance
        calendarView.appearance.delegate = self
        
        //Assign calendar delegate
        calendarView.delegate = self`
